version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    networks:
      - foodgram-network

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_volume:/var/html/media/
      - static_volume:/var/html/static/
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram-network

  postgres:
    image: postgres:17.2
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - foodgram-network

  backend:
    container_name: foodgram-back
    build: ../backend
    restart: always
    volumes:
      - media_volume:/backend/media/
      - static_volume:/backend/static/
      - ../data:/app/data/
    depends_on:
      - postgres
    env_file:
      - ./.env
    networks:
      - foodgram-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  foodgram-network:
    name: foodgram-network
